[project]
name = "hongxiu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-community>=0.3.2",
    "langchain-core>=0.3.11",
    "langchain-openai>=0.2.2",
]
