model_name: qwen-turbo # gpt-4o-mini
lang: 中文
pdf_parser: pymupdf
debug: false
chains:
  summary:
    template:
      system: |
        请阅读并分析我提供的论文，撰写一份全面的总结。总结需涵盖论文的所有主要知识点，并参考以下结构进行：
        1. **研究背景**：简述论文的研究背景和动机，说明研究的主要问题是什么。
        2. **研究方法**：详细描述论文中使用的研究方法和技术。
        3. **实验设计**：如果论文有实验内容，则包含该项，要说明论文的实验设计或数据处理方法。如果没有则删除该项。
        4. **结果分析**：总结论文中提出的主要结果，并解释其意义。
        5. **结论与启示**：概括论文的最终结论，并阐述对该领域研究的影响或启示。
        格式上的要求如下：
        1. 要求总结清晰明了，使用简洁的语言，避免冗长解释。
        2. 每个部分应有条理性和逻辑性，并避免遗漏任何重要的知识点或细节。
        3. 总结需要确保涵盖论文的所有主要信息。
        5. 使用 YAML 格式撰写总结，YAML格式具体如下，不需要包含任何额外的说明或解释。
        6. 不需要包含markdown yaml标记，或者---分隔符。
        7. 如果内容部分包含冒号或特殊字符，需要使用双引号括起来。
        8. 如果包含公式或数学符号、数值，请使用 LaTeX 格式，如：「学习率1×10」，要写成「学习率$1×10$」，注意LaTex部分包含在$符号中。
        9. 键部分不好被括号括起来，如「推理与决策:」，不要写成「(推理与决策):」。

        具体YAML格式如下（其中summary中的内容仅为示意性的，请根据论文设计结构进行设计，并使用中文表达）：

        metadata:
          title: "论文标题"
          authors: "作者1, 作者2, 作者3"
          institution: "作者所在机构"
          date: "如果找到发布日期，则写具体发表日期（yyyy-mm-dd），否则为空"
          tldr: "一句一百字左右的中文概括论文的主要内容"
        summary: (以下为论文总结内容，每段用500字左右的文字概括对应内容)
          研究背景:
            研究问题: (详细描述论文的研究背景和动机，说明研究的主要问题是什么)
            研究难点: (详细描述论文的研究难点)
            相关工作: (详细描述相关工作)
          研究方法:
            介绍: (详细描述论文中使用的研究方法和技术)
            具体: (列出具体的方法)
              (方法1名称): (方法1的详细描述)
              (方法2名称): (方法2的详细描述)
          实验设计: (如果没有实验内容则不要包含该项)
            数据收集：（具体列出使用了哪些数据集以及规模）
              (数据集1名称): (数据集1的规模)
            实验设置：（具体描述实验设置）
            实验过程：（具体描述实验过程，如果有类似于预训练、微调等步骤，则分步列出具体过程名称和过程的介绍）
              (步骤1名称): (步骤1的具体细节)
              (步骤2名称): (步骤2的具体细节)
          结果与分析: （列出论文得出了哪些结果，以及结果细节）
            (结果1名称): (结果1的详细内容)
            (结果2名称): (结果2的详细内容)
          总体结论: (总结论文的最终结论，并阐述对该领域研究的影响或启示)
      user: |
        以下是论文的详细信息：

        {text}

  figures:
    template:
      system: |
        作为一个学术论文资深编辑，请阅读并分析我提供的论文，将其中重要的图表提取出来。
        内容有如下要求：
        1. 发现的图表(Markdown的图片链接)逐一列出；
          1.1 图表链接请不要包含markdown的图片标记，只保留图片链接；
        2. 列出的顺序按照对于帮助理解论文内容的重要性排序，最重要的放前面；
        3. 列出图表的链接、类型、描述、重要性原因；
        4. 其中描述要根据图表介绍和上下文进行总结，需要详细描述，总结中不要提及图片名称，只描述图片内容；
        5. 所有回答请用中文书写。
        6. 结果请只包含YAML格式的内容，不要包含其他内容，也不包括 markdown yaml代码段 之类的标记。
        7. 结果以 YAML 格式输出，格式如下：

        figures:
          - link: 图表链接
            type: 图表类型（FIGURE/TABLE)
            desc: 图表描述
          - link: 图表链接
            type: 图表类型（FIGURE/TABLE)
            desc: 图表描述
      user: |
        以下是论文详细信息：

        {text}
    
  insert_figures:
    template:
      system: |
        作为一个学术论文资深编辑，请根据给出的论文图片信息，帮忙修订所提供的 YAML 格式的论文总结。
        内容有如下要求：
        1. 请根据图片对于理解论文的重要性进行排序，将最重要的图片插入到summary中对应部分的前面。
        2. 请注意提供的figure类型，请只插入图片，而不要插入表格。
        3. 图片插入的格式如下，假设图片链接为 figures/abc.jpg，如果需要插入的段落是 list 中的某个元素，则在该元素前面插入一项同级元素:
          - IMAGE|path/to/abc.jpg
          如果需要插入的段落是 dict 中的某个键值对，则在该键值对前面插入同级键值对:
          IMAGE: path/to/abc.jpg
        4. 插入时，请注意YAML格式的缩进，插入后的格式应符合YAML格式要求。
        5. 请只生成YAML内容，不需要包含任何额外的说明或解释，也不需要包含yaml标记。
        6. 示例：如：
          假如你发现所提供的图片 aaa/bbb/ccc.png 对于所提供的 YAML 格式的论文总结中的「研究方法」中的「下一个句子预测」部分非常重要，请将该图片链接插入到「下一个句子预测」部分的前面，

          原始的 YAML 格式的论文总结相关部分如下：

            ...
            研究方法:
              介绍: BERT模型通过一种名为‘掩码语言模型’(MLM)的预训练目标来克服传统语言模型的单向性限制，同时引入‘下一个句子预测’(NSP)任务以捕捉句子对之间的关系。
              具体:
                掩码语言模型(MLM): 在输入序列中随机掩盖一定比例的单词，并基于上下文预测这些单词，允许模型在上下文中学习双向信息。
                下一个句子预测(NSP): 通过选择连续的句子或随机句子，训练模型理解句子间的关系，从而提高问答和自然语言推理的能力。
            ...

          修订后的 YAML 格式的论文总结相关部分如下：

            ...
            研究方法:
              介绍: BERT模型通过一种名为‘掩码语言模型’(MLM)的预训练目标来克服传统语言模型的单向性限制，同时引入‘下一个句子预测’(NSP)任务以捕捉句子对之间的关系。
              具体:
                掩码语言模型(MLM): 在输入序列中随机掩盖一定比例的单词，并基于上下文预测这些单词，允许模型在上下文中学习双向信息。
                IMAGE: aaa/bbb/ccc.png
                下一个句子预测(NSP): 通过选择连续的句子或随机句子，训练模型理解句子间的关系，从而提高问答和自然语言推理的能力。
            ...
        7. 请检查论文总结 YAML 中， summary 下的结构，如有不应包含的内容，比如并无实验设计，但是 summary 中包含了「实验设计」，请删除这部分内容。
      user: |
        下面是图表信息：

        {figures}

        以下是论文总结的 YAML 格式内容：

        {summary}

        请返回修订后的 YAML 格式的论文总结。

  mindmap:
    template:
      system: |
        请阅读并分析以下提供的学术论文，然后以 YAML 格式生成一个全面且清晰的脑图。脑图应涵盖论文的所有主要知识点，并确保结构清晰、易于理解。包含如下内容：
        1. **论文metadata**：
          - 论文标题、作者、发表日期、机构等信息。这部分信息不要丢失。
        2. **引言部分**：
          - 简要介绍论文的研究背景和动机。
          - 说明论文的主要研究问题或目标。
        3. **方法论**：
          - 描述论文中使用的研究方法和技术。
          - 如果适用，简要说明实验设计、数据收集和处理方法。
        4. **主要发现**：
          - 列出并解释论文中的主要研究结果。
          - 强调关键的数据点、图表或统计分析结果。
          - 用简洁的语言解释这些发现的意义。
        5. **讨论与结论**：
          - 讨论研究结果对当前领域的影响。
          - 指出研究的局限性和未来的研究方向。
          - 总结论文的主要贡献和结论。
        6. **其他重要信息**：（如果有的话）
          - 如果论文中有任何特别重要的图表或数据，请在脑图中提及并简要解释其意义。
          - 如果论文中提到了其他相关研究或理论，请简要说明它们如何支持或反驳当前研究。
        表达上有如下要求：
        1. 清晰性和连贯性：
          - 使用清晰、简洁的语言。
          - 分段落组织内容，每段落有一个明确的主题句。
          - 避免使用过多的专业术语，必要时进行解释。
          - 保持逻辑连贯，使读者能够轻松理解论文的核心内容。
        2. 请使中文撰写脑图内容。
        3. 请只生成脑图内容，不需要包含任何额外的说明或解释，也不需要包含```yaml标记。
        4. 请确保脑图全面且准确地反映了论文的内容，并且易于非专业人士理解。
        5. 注意不要缺失metadata信息。

        格式上要求使用 YAML 格式撰写脑图内容，具体格式如下：

        metadata:
          title: "论文标题"
          authors: "作者1, 作者2, 作者3"
          institution: "作者所在机构"
          date: "发表日期（yyyy-mm-dd）"
          tldr: "一句话概括论文的主要内容"
        mindmap:
          引言部分:
            研究背景: (研究背景和动机)
            研究问题: (研究问题或目标)
          方法论:
            研究方法: (研究方法和技术)
            实验设计:（如果适用）
              数据收集:（如果适用）
                (数据集1名称): (数据集1的介绍)
                (数据集2名称): (数据集2的介绍)
              实验设置:（如果适用）
              实验过程:（如果适用）
                (步骤1名称): (步骤1的介绍)
                (步骤2名称): (步骤2的介绍)
          主要发现:
            研究结果:
              (结果1名称): (结果1的介绍)
              (结果2名称): (结果2的介绍)
            数据分析: (数据点、图表或统计分析结果)
          讨论与结论:
            结果讨论: (研究结果对当前领域的影响)
            研究局限: (研究的局限性和未来研究方向)
          其他重要信息: (如果有的话)
            相关研究: (（如果适用）)
              (研究1名称): (研究1的介绍)
              (研究2名称): (研究2的介绍)
      user: |
        以下是论文的详细信息：

        {text}
