chains:
  summary1:
    model_name: gpt-4o-mini
    template: |
      请阅读并分析我提供的论文，撰写一份全面的总结。总结需涵盖论文的所有主要知识点，并按照以下结构进行：
      1. **研究背景**：简述论文的研究背景和动机，说明研究的主要问题是什么。
      2. **研究方法**：详细描述论文中使用的研究方法和技术。
      3. **实验设计**：说明论文的实验设计或数据处理方法。
      4. **结果分析**：总结论文中提出的主要结果，并解释其意义。
      5. **结论与启示**：概括论文的最终结论，并阐述对该领域研究的影响或启示。
      格式上的要求如下：
      1. 要求总结清晰明了，使用简洁的语言，避免冗长解释。
      2. 每个部分应有条理性和逻辑性，并避免遗漏任何重要的知识点或细节。
      3. 总结需要确保涵盖论文的所有主要信息。
      4. 使用 Markdown 格式撰写总结，不需要包含任何额外的说明或解释。也不需要包含```markdown标记
      5. 请使用中文撰写总结内容。
      6. 确保论文题目为一级标题，其下为作者、发表时间等信息。
      以下是论文的详细信息：
      ---
      {text}
      ---
  summary:
    model_name: gpt-4o-mini
    template: |
      请阅读并分析我提供的论文，撰写一份全面的总结。总结需涵盖论文的所有主要知识点，并按照以下结构进行：
      1. **研究背景**：简述论文的研究背景和动机，说明研究的主要问题是什么。
      2. **研究方法**：详细描述论文中使用的研究方法和技术。
      3. **实验设计**：说明论文的实验设计或数据处理方法。
      4. **结果分析**：总结论文中提出的主要结果，并解释其意义。
      5. **结论与启示**：概括论文的最终结论，并阐述对该领域研究的影响或启示。
      格式上的要求如下：
      1. 要求总结清晰明了，使用简洁的语言，避免冗长解释。
      2. 每个部分应有条理性和逻辑性，并避免遗漏任何重要的知识点或细节。
      3. 总结需要确保涵盖论文的所有主要信息。
      4. 请使用中文撰写总结内容。
      5. 使用 YAML 格式撰写总结，YAML格式具体如下，不需要包含任何额外的说明或解释。
      6. 不需要包含```yaml标记，或者---分隔符。
      7. 如果内容部分包含冒号或特殊字符，需要使用双引号括起来。
      8. 如果包含公式或数学符号、数值，请使用 LaTeX 格式，如：「学习率1×10」，要写成「学习率$1×10$」，注意LaTex部分包含在$符号中。
      YAML格式如下：

      title: "论文标题"
      authors: "作者1, 作者2, 作者3"
      institution: "作者所在机构"
      date: 如果找到发布日期，则写具体发表日期（yyyy-mm-dd），否则为空
      tldr: "一句一百字左右的中文概括论文的主要内容"
      summary: (以下为论文总结内容，每段用500字左右的文字概括对应内容）
        研究背景:
          研究问题: (简述论文的研究背景和动机，说明研究的主要问题是什么)
          研究难点: (简述论文的研究难点)
          相关工作: (简述相关工作)
        研究方法:
          介绍: (详细描述论文中使用的研究方法和技术)
          具体: (列出具体的方法及简述)
            (方法1名称): (方法1的简述)
            (方法2名称): (方法2的简述)
        实验设计:
          数据收集：（具体列出使用了哪些数据集以及规模）
            （数据集1名称）: （数据集1的规模）
          实验设置：（具体描述实验设置）
          实验过程：（具体描述实验过程，如果有类似于预训练、微调等步骤，则分步列出具体过程名称和过程的介绍）
            (步骤1名称): (步骤1的介绍)
            (步骤2名称): (步骤2的介绍)
        结果分析: （列出具体使用了哪些测试以及其结果，以及对结果的分析）
          (测试1名称): (测试1的结果分析)
          (测试2名称): (测试2的结果分析)
        结论与启示: （总结论文的最终结论，并阐述对该领域研究的影响或启示）
          结论: (论文的结论)
          启示: (对该领域研究的影响或启示)

      以下是论文的详细信息：

      {text}

  figures:
    model_name: gpt-4o-mini
    template: |
      作为一个学术论文资深编辑，请阅读并分析我提供的论文，将其中重要的图表提取出来。
      内容有如下要求：
      1. 发现的图表(Markdown的图片链接)逐一列出；
      2. 列出的顺序按照对于帮助理解论文内容的重要性排序，最重要的放前面；
      3. 列出图表的链接、类型、描述、重要性原因；
      4. 其中描述要根据图表介绍和上下文进行总结，需要详细描述，总结中不要提及图片名称，只描述图片内容；
      5. 所有回答请用中文书写。
      6. 结果请只包含YAML格式的内容，不要包含其他内容，也不包括 ```yaml 之类的标记。
      7. 结果以 YAML 格式输出，格式如下：

      figures:
        - link: 图表链接
          type: 图表类型（FIGURE/TABLE)
          desc: 图表描述
        - link: 图表链接
          type: 图表类型（FIGURE/TABLE)
          desc: 图表描述

      以下是论文详细信息：
      ---
      {text}
      ---

  mindmap:
    model_name: gpt-4o-mini
    template: |
      请阅读并分析以下提供的学术论文，然后以 Markdown 格式生成一个全面且清晰的脑图。脑图应涵盖论文的所有主要知识点，并确保结构清晰、易于理解。具体要求如下：
      1. **总体结构**：
        - 使用 Markdown 语法来表示脑图的层级结构。
        - 每个主要部分和子部分都应有明确的标题和内容。
      2. **引言部分**：
        - 简要介绍论文的研究背景和研究动机。
        - 说明论文的主要研究问题或目标。
      3. **方法论**：
        - 描述论文中使用的研究方法和技术。
        - 如果适用，简要说明实验设计、数据收集和处理方法。
      4. **主要发现**：
        - 列出并解释论文中的主要研究结果。
        - 强调关键的数据点、图表或统计分析结果。
        - 用简洁的语言解释这些发现的意义。
      5. **讨论与结论**：
        - 讨论研究结果对当前领域的影响。
        - 指出研究的局限性和未来的研究方向。
        - 总结论文的主要贡献和结论。
      6. **其他重要信息**：
        - 如果论文中有任何特别重要的图表或数据，请在脑图中提及并简要解释其意义。
        - 如果论文中提到了其他相关研究或理论，请简要说明它们如何支持或反驳当前研究。
      格式上有如下要求：
      1. **Markdown 格式**：
        - 使用 Markdown 的列表和嵌套列表来表示脑图的层级结构。
        - 第一级至第三级标题使用 `#`、`##`、`###` 等 Markdown 标记。
        - 第四级及以下的条目使用 `-` 或 `*` 等 Markdown 标记表示。
      2. **清晰性和连贯性**：
        - 使用清晰、简洁的语言。
        - 分段落组织内容，每段落有一个明确的主题句。
        - 避免使用过多的专业术语，必要时进行解释。
        - 保持逻辑连贯，使读者能够轻松理解论文的核心内容。
      3. 请只生成脑图内容，不需要包含任何额外的说明或解释，也不需要包含```markdown标记
      4. 请使用中文撰写脑图内容。
      请确保脑图全面且准确地反映了论文的内容，并且易于非专业人士理解。
      以下是论文的详细信息：
      ---
      {text}
      ---
debug: false
