chains:
  summary:
    model_name: gpt-4o-mini
    template: |
      请阅读并分析我提供的论文，撰写一份全面的总结。总结需涵盖论文的所有主要知识点，并按照以下结构进行：
      1. **研究背景**：简述论文的研究背景和动机，说明研究的主要问题是什么。
      2. **研究方法**：详细描述论文中使用的研究方法和技术。
      3. **实验设计**：说明论文的实验设计或数据处理方法。
      4. **结果分析**：总结论文中提出的主要结果，并解释其意义。
      5. **结论与启示**：概括论文的最终结论，并阐述对该领域研究的影响或启示。
      要求总结清晰明了，使用简洁的语言，避免冗长解释。每个部分应有条理性和逻辑性，并避免遗漏任何重要的知识点或细节。总结需要确保涵盖论文的所有主要信息。
      以下是论文的详细信息：
      ---
      {text}
      ---
  mindmap:
    model_name: gpt-4o-mini
    template: |
      请阅读并分析以下提供的学术论文，然后以 Markdown 格式生成一个全面且清晰的脑图。脑图应涵盖论文的所有主要知识点，并确保结构清晰、易于理解。具体要求如下：
      1. **总体结构**：
        - 使用 Markdown 语法来表示脑图的层级结构。
        - 每个主要部分和子部分都应有明确的标题和内容。
      2. **引言部分**：
        - 简要介绍论文的研究背景和研究动机。
        - 说明论文的主要研究问题或目标。
      3. **方法论**：
        - 描述论文中使用的研究方法和技术。
        - 如果适用，简要说明实验设计、数据收集和处理方法。
      4. **主要发现**：
        - 列出并解释论文中的主要研究结果。
        - 强调关键的数据点、图表或统计分析结果。
        - 用简洁的语言解释这些发现的意义。
      5. **讨论与结论**：
        - 讨论研究结果对当前领域的影响。
        - 指出研究的局限性和未来的研究方向。
        - 总结论文的主要贡献和结论。
      6. **其他重要信息**：
        - 如果论文中有任何特别重要的图表或数据，请在脑图中提及并简要解释其意义。
        - 如果论文中提到了其他相关研究或理论，请简要说明它们如何支持或反驳当前研究。
      格式上有如下要求：
      1. **Markdown 格式**：
        - 使用 Markdown 的列表和嵌套列表来表示脑图的层级结构。
        - 第一级至第三级标题使用 `#`、`##`、`###` 等 Markdown 标记。
        - 第四级及以下的条目使用 `-` 或 `*` 等 Markdown 标记表示。
      2. **清晰性和连贯性**：
        - 使用清晰、简洁的语言。
        - 分段落组织内容，每段落有一个明确的主题句。
        - 避免使用过多的专业术语，必要时进行解释。
        - 保持逻辑连贯，使读者能够轻松理解论文的核心内容。
      3. 请只生成脑图内容，不需要包含任何额外的说明或解释，也不需要包含```markdown标记
      4. 请使用中文撰写脑图内容。
      请确保脑图全面且准确地反映了论文的内容，并且易于非专业人士理解。
      以下是论文的详细信息：
      ---
      {text}
      ---
debug: false